version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: API.Dockerfile
    ports:
      - "5000:80"
    environment:
      - TZ=America/Sao_Paulo

  web:
    build:
      context: .
      dockerfile: Web.Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "4200:80"